### ISSUE TITLE
Calculator generates incorrect recipes for some seeds

### ISSUE THREAD

**Issue by wchill** [wchill/bindingofisaac#1]
example: https://www.reddit.com/r/bindingofisaac/comments/r3d0vx/bag_of_crafting_calculator_for_nintendo_switch/hmbqis5/

**Comment by wchill** [comment]
```
SEED: ffqdxrfg

[ Bomb
  Bomb
  Bomb
  Penny
  Key
  Key
  Dime
  Dime ]
(total 21, ★★☆☆-★★★☆) -> Eye Drops (id 600 ★★★☆)
```

but actually generates Voodoo Head (id 599)

**Comment by wchill** [comment]
```
SEED: t0kg01zf

[ Dime
  Bomb
  Bomb
  Penny
  Penny
  Penny
  Penny
  Golden Bomb ]
(total 20, ★★☆☆-★★★☆) -> Stigmata (id 138 ★★☆☆)
```

but actually generates 9 Volt (116)

**Comment by wchill** [comment]
```
[ Bomb
  Bomb
  Red Heart
  Red Heart
  Soul Heart
  Soul Heart
  Nickel
  Nickel ]
(total 20, ★★☆☆-★★★☆) -> Steam Sale (id 64 ★★☆☆)
```

but actually generates Pentagram (id 51)

**Comment by hailsaturn** [comment]
I'm consistently getting incorrect results trying to cheese for Eden's Blessing. 

Examples: 

```
SEED: 7bvmyw7d

[ Red Heart
  Red Heart
  Soul Heart
  Soul Heart
  Penny
  Nickel
  Nickel
  Key ]
(total 19, ★★☆☆-★★★☆) -> Eden's Blessing (id 381 ★★★☆)
```
But actually generates Host Hat (id 375)


```
SEED: g0rgkxtq

[ Red Heart
  Red Heart
  Soul Heart
  Soul Heart
  Soul Heart
  Nickel
  Bomb
  Bomb ]
(total 21, ★★☆☆-★★★☆) -> Eden's Blessing (id 381 ★★★☆)
```
But actually generates Host Hat (id 375)

```
SEED: g0rgkxtq

[ Soul Heart
  Soul Heart
  Penny
  Nickel
  Bomb
  Bomb
  Bomb
  Bomb ]
(total 20, ★★☆☆-★★★☆) -> Eden's Blessing (id 381 ★★★☆)
```
But actually generates Host Hat (again)

```
SEED: g0rgkxtq

[ Soul Heart
  Soul Heart
  Soul Heart
  Soul Heart
  Soul Heart
  Soul Heart
  Soul Heart
  Penny ]
(total 29, ★★★☆-★★★★) -> Eden's Blessing (id 381 ★★★☆)
```
But actually generates Teleport 2.0 (id 419)

```
SEED: dg9wm41b

[ Soul Heart
  Soul Heart
  Soul Heart
  Penny
  Penny
  Bomb
  Bomb
  Bomb ]
(total 20, ★★☆☆-★★★☆) -> Eden's Blessing (id 381 ★★★☆)
```
But actually generates Host Hat (id 375)

```
SEED: dg9wm41b

[ Red Heart
  Nickel
  Nickel
  Nickel
  Nickel
  Nickel
  Bomb
  Bomb ]
(total 20, ★★☆☆-★★★☆) -> Eden's Blessing (id 381 ★★★☆)
```
But actually generates Restock (id 376)

Not just Eden's blessing. Tried a random arrangement: 
```SEED: dg9wm41b

[ Soul Heart
  Penny
  Nickel
  Nickel
  Nickel
  Nickel
  Bomb
  Bomb ]
(total 21, ★★☆☆-★★★☆) -> Car Battery (id 356 ★★★☆)```

But actually generates Wooden Nickel (id 349)

```
SEED: dg9wm41b

[ Red Heart
  Nickel
  Nickel
  Nickel
  Nickel
  Dime
  Bomb
  Bomb ]
(total 22, ★★☆☆-★★★☆) -> Capricorn (id 307 ★★★☆)
```
But actually generates Taurus (id 299)

I should say: most other items are being generated correctly. But I'm yet to successfully generate Eden's Blessing.

**Comment by wchill** [comment]
@hailsaturn Thanks, this helps a lot. As I expected, the actually generated ID is always less than the one predicted, which seems to confirm one of two things (if not both):
* The random number being calculated is different from the actual one, but just very slightly (or there is floating point error)
* the way the items are binned in game is different from how I am calculating the bins, and the bins in game are actually larger than what I expected.

The info on Eden's Blessing helps a lot because of how big that range is (20-29 total points). I'll take another look at this this weekend.

**Comment by Kirillabaskin** [comment]
@wchill, hi. As i see, this project looks little bit dusty. I'm not so good python dev, but if you would point on LoC which causing problems, maybe i might be helpfull

**Comment by wchill** [comment]
@Kirillabaskin there's no specific line of code that's causing issues.

@hailsaturn I'm attempting to emulate this function using Unicorn to generate some proper test cases. Will report back once I have this working. Currently I have something extremely hacky, but I need to emulate calls to `ItemConfig::GetCollectible()` and `ItemPool::GetPool()`.

**Comment by wchill** [comment]
![image](https://user-images.githubusercontent.com/3746651/154654199-a77b2e8f-bbe8-43f1-936b-6facd539b6ff.png)

**Comment by Kirillabaskin** [comment]
@wchill I founded that QUALITY_RANGES has mistakes in configuration
Like for quality of pickups equal 19 there can be items of quality 1. Now it includes only items of quality 2 and 3

**Comment by Kirillabaskin** [comment]
And now it works !!!!!! I fixed configuration of  QUALITY_RANGES and it works for all my test cases. 
YEAH!!!!

**Comment by wchill** [comment]
@Kirillabaskin can you give me the corrected ranges? I will verify against the binary.

**Comment by Kirillabaskin** [comment]
Sorry, i tried to make pr but forgot about forking your repo.

QUALITY_RANGES = [
    (0, 0, 1),
    (9, 0, 2),
    (15, 1, 2),
    (19, 1, 3),
    (23, 1, 4),
    (27, 2, 4),
    (31, 3, 4),
    (35, 4, 4),
]

**Comment by wchill** [comment]
Ah, that is a very nice catch. I'll write unit tests and push a new version soon.

**Comment by wchill** [comment]
Looks like the web calculator still has a bug.

seed: 7aldagay

pickups:
"Eternal Heart",
"Eternal Heart",
"Key",
"Golden Key",
"Red Heart",
"Bomb",
"Penny",
"Golden Penny"

I got Pay To Play (380) instead of Sacred Heart (182). However, the Python calculator did get this correct.

**Comment by wchill** [comment]
Looks like it works now, going to close this.

**Comment by segthegamer** [comment]
Hi! my girlfriend is asking if you know when will you be updating this mod to version 1.6? Thanks!

**Comment by air-dex** [comment]
I have found an error:

- Platform: Nintendo Switch
- TBoI version: 1.7 (corresponds to v1.7.8a)
- Seed: SYAQX0N1
- Receipe: Bone Heart, Bone Heart, Bone Heart, Bone Heart, Bone Heart, Red Heart, Key, Key.
- Expected: R Key.
- Predicted by the tool: Birthright.
- Birthright already unlocked in the save where I have computed this receipe.

**Comment by Jaelan-prole** [comment]
PC 1.7.8
Seed: XE8GZJZT
Recipe for Gnawed leaf: 1 penny, 2 bombs, 2 hearts, 1 key, 1 pill, 1 soul heart
Gave me Mine Crafter.

Also: 
Seed: MK8K ALJT
Recipe for Midas Touch: 6 bombs, 1 key, 1 card
Gave me Safety Pin.

I've run at least 12 other seeds without issue, at least with the recipes I've used in them for the same items. I haven't documented all of those, but I could if it'd be helpful. 

I truly appreciate this calculator, and think it's fantastic!

**Comment by Et0san** [comment]
Platform : PC (last steam ver.)
SEED: J73Y1RSC

[ Bomb
  Bomb
  Bomb
  Penny
  Red Heart
  Red Heart
  Red Heart
  Red Heart ]

generates Dataminer instead of Clicker.

**Comment by Issac123835** [comment]
Platform : Switch version v1.7
SEED: J73Y1RSC

[ Red Heart
Blue Heart
Coin
Coin
Bomb
Bomb
Bomb
Dime]

generates Sharp Plug instead of Fanny Pack.

**Comment by Zephies90** [comment]
Seed ZFWM VLBM platform version 1.7

{Bomb
Bomb
Bomb
Soul Heart
Soul Heart
Soul Heart
Nickel
Nickel}

Supposed to be Book of Sin instead generates Super Bandage

**Comment by Greasyrat02** [comment]
Platform: Nintendo Switch version 1.7
Seed: 1NAQ PJ4J

[Red Heart
Soul Heart
Soul Heart
Penny
Nickel
Key
Bomb
Card]

Expected Result: Birthright
Actual Result: Larynx
