### ISSUE TITLE
v1.6 support

### ISSUE THREAD

**Issue by wchill** [wchill/bindingofisaac#2]
Following files need to be pulled from update romfs:
* itempools.xml
* items.xml
* items_metadata.xml
* recipes.xml
* stringtable.sta

**Comment by kir-alt** [comment]
Yo its me! Thanks for taking me in consideration <3 good luck on this!

**Comment by kir-alt** [comment]
![image](https://user-images.githubusercontent.com/98668358/162284146-c514b7bc-0a54-455b-96c4-8f25ba67e622.jpeg)


Python script wont work.

**Comment by kir-alt** [comment]
Got the files.

https://cdn.discordapp.com/attachments/123961790529929218/961766802503901265/resources.rar

**Comment by AlexMoel112** [comment]
[files 1.6.zip](https://github.com/wchill/bindingofisaac/files/8457727/files.1.6.zip)

glad to help

**Comment by wchill** [comment]
Implemented in https://github.com/wchill/bindingofisaac/commit/15103ce255f4a3c7ef3e3bdc4f992ff7997b4b70
