### ISSUE TITLE
Switch 1.7 seed issues

### ISSUE THREAD

**Issue by Itnew30** [wchill/bindingofisaac#7]
Hello, so I was trying to finish my tainted cain with this program (isaac physical afterbirth+ on switch with repentance dlc, version 1.7) and the recipes were sometimes not accurate. Today i've seen that the program was updated with the pc functions etc... But now when i'm trying to put my seed, it's described as an incorrect seed. So it's even worse than a not accurate recipe x).

**Comment by wchill** [comment]
@Itnew30 incorrect seed actually was a catchall for "there's an error", not necessarily with the seed itself. I identified an issue a couple days ago and fixed it. Try again
